version: '2'
services:
    buildchaindemo-app:
        image: buildchaindemo
        external_links:
            - buildchaindemo-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/buildchaindemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    buildchaindemo-mysql:
        extends:
            file: mysql.yml
            service: buildchaindemo-mysql
